### PR TITLE
Add Hesperus compatibility

### LINKED ISSUE #38: Crash with Aether II
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderException: java.lang.NoClassDefFoundError: net/minecraft/world/chunk/Chunk

Minecraft: 1.12.2
Forge: 14.23.5.2860
[RoughlyEnoughIDs: 2.0.8](https://www.curseforge.com/minecraft/mc-mods/reid/files/5143492)

[Mixinbooter: 9.1](https://www.curseforge.com/minecraft/mc-mods/mixin-booter/files/5079135)
[Aether II: 0.3.0+build411-universal](https://www.curseforge.com/minecraft/mc-mods/aether-ii/files/2960610)

logs:
[crash-2024-03-06_01.04.48-client.txt](https://github.com/TerraFirmaCraft-The-Final-Frontier/RoughlyEnoughIDs/files/14502022/crash-2024-03-06_01.04.48-client.txt)
[latest.log](https://github.com/TerraFirmaCraft-The-Final-Frontier/RoughlyEnoughIDs/files/14502016/latest.log)
[debug.log](https://github.com/TerraFirmaCraft-The-Final-Frontier/RoughlyEnoughIDs/files/14502015/debug.log)
[launcher_log.txt](https://github.com/TerraFirmaCraft-The-Final-Frontier/RoughlyEnoughIDs/files/14502047/launcher_log.txt)

### PR DESCRIPTION
**Pull request by zeng-github01**
However, the original version uses MixinBootstrap as Mixin support, while REID uses MixinBooter as Mixin support, which will cause conflicts. MixinBooter must be used for the patch to take effect.

[MixinBooter Fork](https://www.curseforge.com/minecraft/mc-mods/hesperus)

Fixes #38

### CODE REVIEW

**Comment by jchung01** [comment]
I would like to mention some things and suggest that compatibility with Phosphor is not/should not be necessary.

First of all, the #38 "incompatibility" doesn't really have anything to do with REID, it's a matter of Phosphor being shaded in the official Aether II mod. However, there is actually a fork of Aether II [here](https://www.curseforge.com/minecraft/mc-mods/the-aether-ii-phosphor-not-included) on CF that does not include Phosphor so users can use whatever lighting mod (Hesperus, Alfheim) they would like. This was discussed in an issue by the same poster in CleanroomMC/MixinBooter#73. I think [PhosphorCrashFix](https://www.curseforge.com/minecraft/mc-mods/phosphorcrashfix) is an alternative method if someone really wishes to use the original Aether II mod.

From what I understand, looking briefly at how you combined REID and Phosphor mixins, you are saying this would allow using MixinBoostrap to load REID. However, this should not be supported because as of 2.1.0 I refactored a lot of mixins to rely on MixinExtras annotations, and as far as I know, MixinExtras is only present if you use MixinBooter. There is also a certain minimum version of MixinExtras that is necessary, which is why the minimum version of MixinBooter is specified. 
(As an aside, I don't even think there are any overlapping mixins between REID and Phosphor that may cause an incompatibility)

In any case, without meaning to sound rude, I don't think this PR is necessary. At worst, if someone really wants to use the original Phosphor mod, they can try launching with PhosphorCrashFix. Feel free to explain otherwise if I missed anything.

**Comment by zeng-github01** [comment]
> I would like to mention some things and suggest that compatibility with Phosphor is not necessary and shouldn't be supported from our side.
> 
> First of all, the #38 "incompatibility" doesn't really have anything to do with REID, it's a matter of Phosphor being shaded in the official Aether II mod. However, there is actually a fork of Aether II [here](https://www.curseforge.com/minecraft/mc-mods/the-aether-ii-phosphor-not-included) on CF that does not include Phosphor so users can use whatever lighting mod (Hesperus, Alfheim) they would like. This was discussed in an issue by the same poster in [CleanroomMC/MixinBooter#73](https://github.com/CleanroomMC/MixinBooter/issues/73). I think [PhosphorCrashFix](https://www.curseforge.com/minecraft/mc-mods/phosphorcrashfix) is an alternative method if someone really wishes to use the original Aether II mod.
> 
> From what I understand, looking briefly at how you combined REID and Phosphor mixins, you are saying this would allow using MixinBoostrap to load REID. However, this should not be supported because as of 2.1.0 I refactored a lot of mixins to rely on MixinExtras annotations, and as far as I know, MixinExtras is only present if you use MixinBooter. There is also a certain minimum version of MixinExtras that is necessary, which is why the minimum version of MixinBooter is specified. (As an aside, I don't even think there are any overlapping mixins between REID and Phosphor that may cause an incompatibility)
> 
> In any case, without meaning to sound rude, I don't think this PR is necessary. At worst, if someone really wants to use the original Phosphor mod, they can try launching with PhosphorCrashFix. Feel free to explain otherwise if I missed anything.

You read it wrong, this does not require us to use MixinBoostrap to load REID, but requires using the Phosphor branch that supports MixinBooter

After all we can't support an old Mixin framework

**Comment by zeng-github01** [comment]
@jchung01 This patch just provides a Mixin class that supports both Phosphor and REID Chunk Class and more

**Comment by jchung01** [comment]
So you are saying this is to support specifically the old, original version of Phosphor? Because Hesperus loads fine alongside REID (using MixinBooter). Even then, adding Phosphor Crash Fix lets the original Phosphor mod load fine with whatever mixin mods, including REID.

**Comment by zeng-github01** [comment]
> So you are saying this is to support specifically the old, original version of Phosphor? Because Hesperus loads fine alongside REID (using MixinBooter). Even then, adding Phosphor Crash Fix lets the original Phosphor mod load fine with whatever mixin mods, including REID.
> 
> If there are any specific mixins that aren't loaded when REID and Phosphor/Hesperus are present, then patch those specific ones. No need to rewrite mixins that will be applied independently from each mod.

It seems that I just got the wrong information when debugging. Even without patching, Hesperus can load normally.

I first thought it was a crash caused by patch failure, but it doesn't seem to be the case.

**Comment by zeng-github01** [comment]
@jchung01  The most recent commit records are just for modifying the commit message

**Comment by jchung01** [comment]
Load order should have no effect here, REID and Phosphor modify different methods and/or targets within the method. I can verify there are no mixin injection errors: this is a debug.log with just Hesperus, REID 2.1.0, and MixinBooter 8.6 https://mclo.gs/FesMD3a. Unless you know of a specific mixin injection that fails, there should be no issue with REID and Hesperus.

**Comment by zeng-github01** [comment]
> 加载顺序在这里应该没有影响，REID 和 Phosphor 修改了方法中的不同方法和/或目标。我可以验证没有 mixin 注入错误：这是一个只有 Hesperus、REID 2.1.0 和 MixinBooter 8.6 https://mclo.gs/FesMD3a debug.log（我正在使用我最近提交的 2.1.0 之后的构建，但这应该无关紧要）。除非您知道特定的混合素注射失败，否则 REID 和 Hesperus 应该没有问题。
> 
> 您甚至可以运行环境并验证反编译的类是否具有来自两个 mod 的所有 mixin，没有问题。`-Dmixin.debug.export=true`



> Load order should have no effect here, REID and Phosphor modify different methods and/or targets within the method. I can verify there are no mixin injection errors: this is a debug.log with just Hesperus, REID 2.1.0, and MixinBooter 8.6 https://mclo.gs/FesMD3a (I am using a build off my most recent commit past 2.1.0, but that shouldn't matter). Unless you know of a specific mixin injection that fails, there should be no issue with REID and Hesperus.
> 
> You can even run the environment with and verify the decompiled classes have all the mixins from both mods with no issue.`-Dmixin.debug.export=true`

In this case, close this PR

**Pull request closed without merging**
