### PR TITLE
Added support for Scape and Run: Parasites

### LINKED ISSUE #4: Scape & Run: Parasites nodes cannot overwrite biomes with their own.
Quote, re-CurseForge comment;
https://www.curseforge.com/minecraft/mc-mods/reid?comment=20

> Scape and Run: Parasite (SRP for short) has a gameplay mechanic where a "node" appears and starts to replace the biome with its own to spread the 'infestation'.
The issue is, when JEID (or REID) is installed it cant override the biomes with its own biome.
also i found issue #175 on JEID's github: https://github.com/DimensionalDevelopment/JustEnoughIDs/issues/175

> i didnt know SRP wasnt open-source, but they have a discord where they are discussing issues with the mod.

### PR DESCRIPTION
**Pull request by Axis-Denied**
This commit changes how SRP changes biomes by referring to REID's new biome array instead of the old one. It fixes both the Node and the Biome Purifier failing to work with the new chunk format.
Fixes #4

Let me know if there are any issues with the code!

### CODE REVIEW

**Comment by jchung01** [comment]
Honestly, I didn't even know SRP source was available through Modrinth (as 3rd party downloads are disabled on CF). Anyways, it looks good to merge, but I'll make a follow-up PR later to bring it more in line with the other mod mixins.

**Comment by Axis-Denied** [comment]
Thanks! The Modrinth idea was actually from Modrome (or Vetpetmon, I believe he was discussing this issue with you earlier?)

**Comment by Vetpetmon** [comment]
> Thanks! The Modrinth idea was actually from Modrome (or Vetpetmon, I believe he was discussing this issue with you earlier?)

Yes, you can thank me, Dhan, the other developers, and I have given this repository permission to use SRP's code to fix this issue that's been haunting us for over 2 years. Thank you!

**Comment by jchung01** [comment]
The following suggestion is only tangentially related, but I figured it would be worth mentioning. If the intention in `ParasiteEventWorld.positionToBiome()` is to "reset" the Infected Biome to its original, the following line of code:
```
worldIn.getChunk(pos).getBiomeArray()[inChunkZ << 4 | inChunkX] = (byte) Biome.getIdForBiome(Biomes.PLAINS);
```
could be changed to this:
```
Biome original = worldIn.getBiomeProvider().getBiome(pos, Biomes.PLAINS);
worldIn.getChunk(pos).getBiomeArray()[inChunkZ << 4 | inChunkX] = (byte) Biome.getIdForBiome(original);
```
to retrieve the cached biome from the `BiomeProvider`. This should properly "reset" the infected biome to whatever biome originally generated there instead of hardcoding it to set it to Plains.
@Vetpetmon feel free to forward this code to Dhanantry or whoever else develops the code if this is a desirable change.

**Pull request merged**
